RedHatInsights/ros-frontend

src/Routes.js
src/Routes/SamplePage/SamplePage.js
src/index.html

@gnurag, added API request using fetch instead of `axios` and render result into simple table. 
Currently, I am just making API request for /api/inventory/v1/hosts.

Use fetch+convert samplePage to smart component

---

package-lock.json
package.json
src/App.scss
src/Components/EmptyStateDisplay/EmptyStateDisplay.js
src/Components/RosTable/ExpandedRow.js
src/Components/RosTable/ProgressScoreBar.js
src/Components/RosTable/RosTable.js
src/Components/RosTable/RosTable.scss
src/Routes/RosPage/RosPage.js
src/constants.js
src/index.html

Attaching below screenshot for reference:
EDIT -
There are couple of things need to be fixed.

Expanded table render

---

src/App.js
src/Components/RosTable/RosTable.js
src/Components/RosTable/redux/actions.js
src/Components/RosTable/redux/index.js
src/Components/RosTable/redux/systemsTableReducer.js
src/Routes/RosPage/RosPage.js
src/constants.js
src/store/index.js

Fixes [RHIROS-19](https://issues.redhat.com/browse/RHIROS-19)
+ adding @karelhala into loop

implement redux for table rendering

---

src/Components/RosTable/ProgressScoreBar.js
src/Components/RosTable/RosTable.js

Refs to [ros-backend/20](https://github.com/RedHatInsights/ros-backend/pull/20)

ROS-60 Update score calculation

---

src/Components/RecommendationRating/RecommendationRating.js
src/Components/RecommendationRating/RecommendationRating.scss
src/constants.js

System Detail Page needs to import this component -
```
import RecommendationRating from '../../Components/RecommendationRating/RecommendationRating';
<RecommendationRating system={  system } />
```
This system object must include `rating`.
Pending work:
PR raised - https://github.com/RedHatInsights/ros-backend/pull/37

add recommendation_rating component

---

src/Routes/RosPage/RosPage.js

This change should go into the main branch after backend PR RedHatInsights/ros-backend/pull/53

rename field recommendation_count as per API change

---

src/Routes/RosPage/RosPage.js

Backend change in : https://github.com/RedHatInsights/ros-backend/pull/55

RHIROS-100 Sort by state and number_of_recommendations

---

src/Components/SystemDetail/SystemDetail.js

+ adding @karelhala into loop for review.

Refs RHIROS-114 - revert prev change & use inventory_id from redux

---

.travis/custom_release.sh

+ adding @karelhala into loop for review.

edit release script to consider PROD branches

---

config/dev.webpack.config.js
config/prod.webpack.config.js
src/Components/SystemDetail/SystemDetail.js
src/Components/SystemDetail/SystemRecommendations.js
src/Routes/RosSystemDetail/RosSystemDetail.js

+ adding @karelhala into loop for review

expose system detail component

---

src/Components/ServiceNotConfigured/ServiceNotConfigured.js
src/Components/ServiceNotConfigured/ServiceNotConfigured.scss
src/Components/SystemDetail/SystemRecommendations.js
src/store/systemRecs.js

Added empty state to show 'Service is not configured'. With the commit changes, it looks like -
+ adding @karelhala & @terezanovotna for review

Refs #143 - empty state component to show service not configured

---

src/Components/SystemDetail/SystemRecommendations.js
src/Utilities/api.js
src/store/systemRecs.js

+ adding @karelhala into loop for review

RHIROS-165 - hide error notification on detail page when 404

---

src/App.js
src/Routes/RosPage/RosPage.js
src/Routes/RosSystemDetail/RosSystemDetail.js
src/constants.js

For reference, adding below screenshots:
1. Systems List:
2. System Detail Page:
For ROS, 
- Two roles available 1. Resource Optimization administrator 2. Resource Optimization user
- Currently includes only wildcard permissions against resource. That means User won't be able to create custom roles on these permissions.
- By default, for both roles it adds read permission for inventory application i.e "inventory:*:read" so I have only checked ros side read permission wherever required.
Here is rbac config PR - https://github.com/RedHatInsights/rbac-config/pull/174
+ adding @karelhala & @terezanovotna into loop for UI review

RHIROS-34 - apply RBAC permissions while rendering

---

src/Components/SystemDetail/RecommendationsTable.js
src/Components/SystemDetail/RecommendationsTable.scss

RHIROS #181 - Add titles to expanded recommendations

---

package-lock.json
package.json
src/App.js

+adding @karelhala into loop for review

remove cookie condition added for private beta

---

config/dev.webpack.config.js
config/prod.webpack.config.js
src/Components/SystemDetail/SystemDetail.js
src/Components/SystemDetail/SystemRecommendations.js
src/Routes/RosSystemDetail/RosSystemDetail.js

* expose system detail component
* register systemRecsReducer to display data under inventory
* apply sassPrefix to fix styling on inventory page
* enable inventory link on system detail page
* make use of useSelector in systemDetail

expose system detail component (#40)

---

src/Components/ServiceNotConfigured/ServiceNotConfigured.js
src/Components/ServiceNotConfigured/ServiceNotConfigured.scss
src/Components/SystemDetail/RecommendationsTable.js

1. Modify empty state message "**No recommendations**
No known recommendations affect this system. "  to "**No recommendations**
This system isn’t affected by any known recommendations."
2. Modify message "**Resource optimization is not yet configured**
Activate application in the Service Enablement Dashboard" to "
**Resource optimization isn’t configured yet**
To start configuration, activate this application in the Service Enablement Dashboard.
[Start configuration]"
+adding @terezanovotna into loop for UX review.

RHIROS-193 - edit messages for empty states

---

src/Components/RosTable/SystemState.js
src/Routes/RosPage/RosPage.js
src/store/entitiesReducer.js

Screenshot for reference:
+ adding @karelhala, @terezanovotna and @kuklas into loop for review

RHIROS-268 - add icons for system states

---

src/App.js
src/Routes/RosPage/RosPage.js
src/Utilities/api.js
src/constants.js
src/store/actions.js
src/store/isConfigured.js
src/store/reducers.js

With this commit changes, 
it will show an empty state on ROS landing page which includes configuration/installation steps to enable ROS for any system(s).
Screenshot for reference - 
adding @karelhala, @terezanovotna and @kuklas into loop for review
Edit - Required backend [PR-104](https://github.com/RedHatInsights/ros-backend/pull/104)  change

RHIROS-244 - is_configured API to verify no ROS systems exist

---

src/Components/RosTable/ExpandedRow.js
src/Routes/RosPage/ros-page.scss
src/constants.js
src/store/entitiesReducer.js

Card:
https://issues.redhat.com/browse/RHIROS-382
Tereza and Pau have approved the changes, discussion link: https://ansible.slack.com/archives/C01C1GVT3TP/p1636448820092600

handling no data UI for utilization  bars

---

.travis.yml
package-lock.json
package.json
src/AppEntry.js
src/store/index.js

**Changes included in the release**
*  Fix for the redux-store error [RHIROS-388](https://issues.redhat.com/browse/RHIROS-388)
* engines check in package.json, travis node version update 
* Bump @redhat-cloud-services/frontend-components-config from 4.4.1 to 4.5.2 
* updated travis.yml to remove slack notification step

Stable to Prod-Beta Release

---

src/Components/RosTable/SystemState.js

Added new state for system: Under pressure
Card: https://issues.redhat.com/browse/RHIROS-421
**Note:**
We can review and merge this PR as it won't break anything and I have checked that we are using same state name as backend

RHIROS-421 - added new state 'Under pressure' for system

---

src/Routes/RosPage/RosPage.js
src/constants.js

https://issues.redhat.com/browse/RHIROS-362
Screenshots:

added logic for enabling state filter

---

README.md
src/Components/RosTable/DiskUsage.js
src/Components/RosTable/DiskUsage.scss
src/Components/RosTable/SystemState.js
src/Components/ServiceNotConfigured/ServiceNotConfigured.js
src/Components/SystemDetail/RecommendationsTable.js
src/Components/SystemDetail/RecommendationsTable.scss
src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
src/Routes/RosPage/RosPage.js
src/constants.js

**Release Notes:**
* Changed API endpoint from v0 to v1
* added new state - under pressure
* Updated disk utilization to show raw number instead of percentage
* updated Suggestion page UI to handle \n
* updated ROS not configured steps
* Enabled state filtering

Stable to Prod-beta

---

src/Components/RosTable/ExpandedRow.js
src/Components/RosTable/ExpandedRow.test.js
src/Components/RosTable/__snapshots__/ExpandedRow.test.js.snap
src/Routes/RosSystemDetail/RosSystemDetail.js
src/store/entitiesReducer.js

**Details**
removed IO wait from expanded view and detail screen
jira: https://issues.redhat.com/browse/RHIROS-464
**Screenshots**

RHIROS-464 removed IO wait from expanded view and detail screen

---

src/Routes/RosPage/RosPage.js

Details:
Fixed the default filtering to name
Jira: https://issues.redhat.com/browse/RHIROS-458
Screenshot:

RHIROS-458 fixed default filtering to name

---

package-lock.json
package.json
src/Routes/RosPage/RosPage.js
src/constants.js

This PR includes code to handle the params passed by Dashboard page to filter systems accordingly based on the state.
**Dashboard side PR:** https://github.com/RedHatInsights/insights-dashboard/pull/285
**Jira:** https://issues.redhat.com/browse/RHIROS-489
https://reactjs.org/docs/react-component.html#componentdidmount
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get
https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState
* Easiest way to test this PR is by appending query param to the ros page URL
For eg:
`https://stage.foo.redhat.com:1337/insights/ros?state=suggestions`
`https://stage.foo.redhat.com:1337/insights/ros?state=waiting`
* In case you want to test end to end locally then please DM me on slack. …

RHIROS-489 handling query params for state filter

---

src/Routes/RosPage/RosPage.js

fixed column rename issue on smaller screen
Jira: https://issues.redhat.com/browse/RHIROS-487
Slack conversation: https://ansible.slack.com/archives/C023VGW21NU/p1643376300933349
Data Label : https://codepen.io/paulfarino/pen/LNPPQg
https://drive.google.com/file/d/1pMHx8UhPsWXAi788Otuw5aQjDXQJDKQF/view?usp=sharing

RHIROS-487 fixed column rename issue on smaller screen

---

src/Components/RosTable/ExpandedRow.js
src/Components/RosTable/ExpandedRow.test.js
src/Components/RosTable/__snapshots__/ExpandedRow.test.js.snap
src/Routes/RosSystemDetail/RosSystemDetail.js
src/Routes/RosSystemDetail/ros-details-page.scss

RHIROS-510 add state value in details page

---

.travis/custom_release.sh

Had a discussion with team around deploying to stage beta/stable together whenever changes are merged to main branch as we have only one env for testing now.
Updated the  custom_release.sh file for same to push to both stage envrionments when we merge changes to main branch.
Based on the slack conversation [here](https://ansible.slack.com/archives/C023VGW21NU/p1646639788659339)  I have removed the reference to ci as we only need qa reference to deploy to stage env.

updated custom_release.sh for stage beta/stable env

---

src/constants.js

Waiting for https://github.com/RedHatInsights/ros-backend/pull/202

RHIROS-535 - enable sorting on os column

---

src/Components/SystemDetail/RecommendationsTable.js
src/Components/SystemDetail/RecommendationsTable.scss
src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap

JIRA Card - [https://issues.redhat.com/browse/RHIROS-609](https://issues.redhat.com/browse/RHIROS-609)
**Idling State:**
**Undersized State:**
**Under-Pressure State:**

RHIROS-609 modify UI for suggestions

---

src/Components/Reports/Common/SystemsTablePage.js
src/Components/Reports/Common/__snapshots__/SystemsFirstPage.test.js.snap
src/Components/Reports/Common/__snapshots__/SystemsTablePage.test.js.snap
src/Components/Reports/Common/styles.js
src/Components/Reports/Util.js
src/Components/Reports/Util.test.js

Fixed last reported format in reports
**Jira:** https://issues.redhat.com/browse/RHIROS-625
https://drive.google.com/file/d/1rjTn2NZQLTf6DBCRGkdPz29m8si_Pyme/view?usp=sharing

RHIROS-625 fix reported date format in reports

---

src/Components/HistoricalDataChart/Util.js
src/Components/HistoricalDataChart/Util.test.js
src/Components/HistoricalDataChart/UtilTestData.js

https://issues.redhat.com/browse/RHIROS-632

RHIROS-632 fixed chart logic to show latest record

---

package-lock.json
package.json
src/Components/HistoricalDataChart/HistoricalDataChart.js
src/Components/HistoricalDataChart/HistoricalDataChart.scss
src/Components/HistoricalDataChart/Util.js
src/Components/HistoricalDataChart/Util.test.js
src/Components/HistoricalDataChart/UtilTestData.js
src/Components/Reports/DownloadReport.js
src/Components/Reports/SystemsPDFReport.js
src/Components/Reports/Util.js
src/Components/Reports/Util.test.js
src/Routes/RosPage/RosPage.js
src/Routes/RosSystemDetail/RosSystemDetail.js
src/Routes/RosSystemDetail/ros-details-page.scss
src/Utilities/api.js
src/constants.js

main --> prod-beta historical changes and minor fix

main --> prod-beta historical changes and minor fix

---

src/store/systemRecs.js

https://issues.redhat.com/browse/RHIROS-647

RHIROS-647  minor bug fix related to suggestions store

---

package-lock.json

updated minimist package to fix critical vulnerability.
**More info:**
https://github.com/advisories/GHSA-xvch-5gv4-984h
https://www.npmjs.com/package/minimist
**Jira:** https://issues.redhat.com/browse/RHIROS-650

Rhiros 650 fix critical vulnerability

---

src/Components/Reports/Common/DescriptionList.js
src/Components/Reports/Common/ExecutiveFirstPage.js
src/Components/Reports/Common/ExecutiveSecondPage.js
src/Components/Reports/Common/IconCanvas.js
src/Components/Reports/Common/styles.js
src/Components/Reports/ExecutivePDFReport.js
src/Components/Reports/ExecutiveePDFReport.scss
src/Components/Reports/Util.js
src/Components/Reports/Util.test.js
src/Components/Reports/UtilTestData.js
src/Routes/RosPage/RosPage.js
src/Routes/RosPage/ros-page.scss
src/Utilities/api.js
src/constants.js

Jira: https://issues.redhat.com/browse/RHIROS-600
https://drive.google.com/file/d/18C9-L8u4E2GTl6T4LgShS6cwgPHxXRmu/view?usp=sharing

RHIROS-600  Executive report

---

src/Components/Reports/Util.js
src/Components/Reports/Util.test.js

https://issues.redhat.com/browse/RHIROS-600

REF-RHIROS-600 updated percentage to float values

---

src/Components/Reports/Common/ExecutiveFirstPage.js

removed text from pie chart in report
Jira: https://issues.redhat.com/browse/RHIROS-686
**Screenshot:**
https://github.com/RedHatInsights/frontend-components/blob/95cee1de51/packages/pdf-generator/src/components/Chart.js#L96
https://codesandbox.io/s/agitated-swanson-9jzm4e?file=/index.js

RHIROS-686 removed text from pie chart in report

---

deploy/frontend.yaml

**Jira:** https://issues.redhat.com/browse/RHIROS-666
**Documentation**: 
https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_deploy

RHIROS-666 added frontend.yaml file in deploy folder

---

config/dev.local.webpack.config.js
package-lock.json
package.json

updated frontend-components-config to latest version so that that API request from ros-frontend to local ros-backend includes the org_id in the top level object of identity header.
Refer this convention for more details: https://ansible.slack.com/archives/C03B7U5AE67/p1657183451755079

updated frontend-components-config to latest version

---

src/constants.js

updated getting stated URL as per discussion [here](https://ansible.slack.com/archives/C01C1GVT3TP/p1662534998181449?thread_ts=1662456323.450929&cid=C01C1GVT3TP)
https://issues.redhat.com/browse/RHIROS-799

RHIROS-799 fixed getting started URL

---

config/dev.local.webpack.config.js
package-lock.json
package.json
src/Components/Reports/UtilTestData.js
src/constants.js

This PR pushes changes from main env to prod-beta.
It includes:
* update in the frontend-config library 
* Bug fix https://issues.redhat.com/browse/RHIROS-799

main --> prod-beta

---

src/Components/Reports/ExecutivePDFReport.js
src/Components/RosTable/RenderColumn.js
src/Components/RosTable/RenderColumn.scss

added stale info in the systems page
**Jira:** 
https://issues.redhat.com/browse/RHIROS-622

Rhiros 622 stale systems info

---

src/Components/Reports/Common/DescriptionList.js
src/Components/Reports/Common/ExecutiveFirstPage.js
src/Components/Reports/Common/ExecutiveSecondPage.js
src/Components/Reports/Common/ExecutiveThirdPage.js
src/Components/Reports/Common/InstancesTable.js
src/Components/Reports/Common/styles.js
src/Components/Reports/Constants.js
src/Components/Reports/DownloadReport.js
src/Components/Reports/ExecutivePDFReport.js
src/Components/Reports/SystemsPDFReport.js
src/Components/Reports/Util.js
src/Components/Reports/Util.test.js
src/Routes/RosPage/RosPage.js
src/constants.js

Executive report V2
Jira: 
https://issues.redhat.com/browse/RHIROS-707
https://issues.redhat.com/browse/RHIROS-778
Screenshot:

added executive report page for instances

---

src/constants.js

Changes:
1. Updated constants.js with RHEL 8.6, 9.0
Additional:
- NA

RHIROS-700 | Add latest RHEL releases for filtering

---

package-lock.json
package.json
src/Components/SystemDetail/SystemRecommendations.js

Few of the packages were old and hence were creating problem while running `npm install` command. I have updated the package to fix the issue and also it fixes few of the vulnerabilities.
I have created a card in backlog to prioritise and fix rest of the vulnerabilities.
https://issues.redhat.com/browse/RHIROS-904
* Checkout the branch
* Remove `node modules` folder
* Run `npm install` command, it should install the mentioned packages successfully
* Run `npm start` command and check if frontend is working properly.
*

RHIROS-906 updated packages to fix local setup and vulnerabilities

---

src/Components/Reports/Common/ExecutiveFirstPage.js
src/Components/Reports/Common/ExecutiveSecondPage.js

* Added non-psi system count in the executive report , **Jira:** https://issues.redhat.com/browse/RHIROS-778
* Updated text as per the [document here](https://docs.google.com/document/d/1X75_NVGHKkwgS3ZVkXVe4oRzrUj402YRN18D14ZJoMo/edit#).

Rhiros 778 add non psi count

---

src/Routes/RosPage/RosPage.js

(cherry picked from commit badfb7990a4c0e8046ef7ff2e504cbc739df31e8)

[prod-beta-push] RHIROS-905 - fix host API 400 error (#149)

---

.github/pull_request_template.md

A PR creation template for ROS front-end repo

RHIROS-840 | Add a Github PR creation template

---

src/Components/Reports/Common/ExecutiveFirstPage.js

To push the color fix issue https://issues.redhat.com/browse/RHIROS-909 from main to prod-beta branch

main ===> prod-beta

---

src/Routes/RosPage/RosPage.js

OS filter will show versions of systems that are registered with ROS.

RHIROS-919 implement custom OS filter logic

---

src/Components/HistoricalDataChart/HistoricalDataChart.js

**Jira:** https://issues.redhat.com/browse/RHIROS-690

added date info in chart tooltip

---

src/Routes/RosSystemDetail/RosSystemDetail.js
src/store/entityDetailReducer.js

As an ongoing effort to optimize apps, this PR replaces the app info from front-end components and just imports it locally.
There should be no change in behavior/ flow
Just performance/optimization effort.

chore(RHIF-172):Remove App info|Optimization effort

---

src/constants.js

Where links to Insights, Console, Cost & Subscriptions docs exist, this PR updates the url to the 2023 version
1. Fixes [RHIROS-982 ](https://issues.redhat.com/browse/RHIROS-982) 

update docs versions for Insights, Console, Cost & Subscriptions

---

.github/workflows/codeql.yml
package-lock.json
package.json
src/Components/HistoricalDataChart/HistoricalDataChart.js
src/Routes/RosPage/RosPage.js
src/Routes/RosSystemDetail/RosSystemDetail.js
src/constants.js
src/store/entityDetailReducer.js

Prod beta release

---

src/App.js
src/Routes/RosPage/RosPage.js
src/Routes/RosSystemDetail/RosSystemDetail.js
src/Utilities/api.js

main to prod-beta

---

src/Routes/RosPage/RosPage.js

RHIROS-1041 show OS versions in desc order while filtering using dropdown

---

src/constants.js

updated getting started link for ROS

fix: updated getting started link for ROS

---

src/constants.js

fix: updated getting started link for ROS (#205)

---

src/Routes.js

fix routing to redirect to ROS page

---

package-lock.json
package.json

updated packages with vulnerabilities
Jira: https://issues.redhat.com/browse/RHIROS-1095
few of the packages we are using got vulnerabilities and this PR updates those packages to fix the same.

updated packages with vulnerabilities

---

src/Components/RosTable/RenderColumn.js

RHIROS-445 use TableComposable component in diskUsageData function

---

src/Routes/RosSystemDetail/RosSystemDetail.js

Jira: https://issues.redhat.com/browse/RHCLOUD-26437

Remove async lifecycle hook for ROS Details route.

---

src/Components/RosTable/RenderColumn.js

https://issues.redhat.com/browse/RHIROS-1215
It is a bug fix we need as part of card https://issues.redhat.com/browse/RHIROS-1215

Ref-RHIROS-1215 added link to group name column value

---

src/Components/Reports/Constants.js
src/Components/Reports/DownloadSystemsReport.js
src/Components/Reports/Util.js
src/Components/Reports/Util.test.js
src/Components/Reports/UtilTestData.js
src/Routes/RosPage/RosPage.js
src/Utilities/api.js

RHIROS 1216 filter by group https://issues.redhat.com/browse/RHIROS-1216

RHIROS 1216 filter by group

---

src/Routes/RosPage/RosPage.js

Implements https://issues.redhat.com/browse/ESSNTL-4494.
This improves how RosTable works with InventoryTable: the group filter is now utilised from Inventory.
The group filter should be aligned with the InventoryTable implementation. Ideally, the component must be updated separately in Inventory and the automatically propagated to ROS. In order to do this, we remove the custom implementation of the filter and unhide the "hostGroupFilter". If users apply the group filter, the filter value will be propagated to "getEntities" where the value can be further passed to an API call.

fix(ESSNTL-4494): Make the Group filter searchable

---

pr_check.sh

Here is the Jira Ticket: https://issues.redhat.com/browse/RHIROS-1114
Changing the maker name so that we can collect new test cases for UI tests (those are navigation tests, which will check the basic navigation)

RHIROS-1114 Updating marker name to collect more tests in the ros-frontend repo

---

src/App.js
src/Components/InstanceTypes/SuggestedInstanceTypesTable.js
src/Components/SystemDetail/SystemRecommendations.js
src/Routes.js
src/Routes/RosPage/RosPage.js
src/Routes/RosSuggestedInstanceTypes/RosSuggestedInstanceTypes.js
src/Utilities/api.js
src/constants.js
src/store/actions.js
src/store/isConfigured.js
src/store/reducers.js
src/store/suggestedInstanceTypes.js

[RHIROS-1163](https://issues.redhat.com/browse/RHIROS-1163)

RHIROS-1163 RHIROS-1222 add suggested instance types table

---

README.md
package.json

updated README.md

---

src/Components/InstanceTypes/SuggestedInstanceTypesTable.js
src/Utilities/api.js
src/constants.js

[RHIROS-1164](https://issues.redhat.com/browse/RHIROS-1164)

RHIROS-1164 implement sorting on suggested instance types table

---

src/Components/InstanceTypes/SuggestedInstanceTypesTable.js
src/Utilities/api.js

[RHIROS-1165](https://issues.redhat.com/browse/RHIROS-1165)

RHIROS-1165 implement filters on suggested instance type page

---

src/Components/RosTable/RenderColumn.js
src/constants.js
src/store/entitiesReducer.js

Jira: https://issues.redhat.com/browse/RHINENG-5152
Currently, the [entitiesReducer.js file](https://github.com/r14chandra/ros-frontend/blob/3b5fc9c0b2cd56f25386df173b28d43430fc886c/src/store/entitiesReducer.js) contains many functions which are related to UI rending. It will be good to extract them into a separate file to improve readability.

RHINENG-5152 refine entitiesReducer.js file

---

src/App.js
src/Routes/RosSuggestedInstanceTypes/RosSuggestedInstanceTypes.js
src/Routes/RosSystemDetail/RosSystemDetail.js

This updates the page titles according to this [ticket](https://issues.redhat.com/browse/RHINENG-9387) and [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)

fix(RHINENG-9387): update page titles

---

src/Components/Reports/Common/SystemsFirstPage.js
src/Components/Reports/Common/SystemsTablePage.js
src/Components/Reports/DownloadReport.js
src/Components/Reports/SystemsPDFReport.js
src/Components/Reports/Util.js
src/Components/RosTable/RenderColumn.js
src/Routes/RosPage/RosPage.js

Jira: https://issues.redhat.com/browse/RHINENG-10418

RHINENG-10418 workspaces feature flag

---

README.md

updated Deployment section of README.md

---

deploy/frontend.yaml

Update clowdapp config to use konflux generated image

---

src/Routes/RosPage/RosPage.js

The Browser title should reset to `Resource Optimisation - Business`

RHINENG-5154 fix landing page browser title

---

.gitignore
README.md
src/Components/RosPopover/RosPopover.js
src/Routes/RosPage/RosPage.js

* add helper icon with ros product doc link
* README and gitignore update
**Jira:** https://issues.redhat.com/browse/RHINENG-14773

RHINENG-14773 add helper icon with ros product doc link

---

.gitmodules
.tekton/ros-frontend-pull-request.yaml
.tekton/ros-frontend-push.yaml

RHINENG-16164 chore(build): use shared Dockerfile
Jira: [RHINENG-16164](https://issues.redhat.com/browse/RHINENG-16164)

RHINENG-16164 chore(build): use shared Dockerfile

---

package-lock.json
package.json

Fixes #RHINENG-16618 - update frontend-components-utilities to 5.0.13

---

.tekton/ros-frontend-pull-request.yaml
.tekton/ros-frontend-push.yaml

https://issues.redhat.com/browse/KONFLUX-2264

Fixes #RHINENG-17125 - add shell & unicode sast pipeline tasks
