- src/Routes/RosPage/RosPage.js
- src/constants.js
Earlier we were fetching host records from inventory but, now we have our ros api, so it would be apt to rename the constant here. Also, since we test on `https://ci.foo.redhat.com:1337/insights/ros` so, the api url shouldn't be localhost but just `/api` as it will be then mapped to the same url via `insights-proxy`.
> Update ros api root constant

- src/constants.js
This change is dependent on ros-backend [PR#10](https://github.com/RedHatInsights/ros-backend/pull/10/). Once v0 api is in place in the backend, this change should get in then.
> Update root api url

- src/Components/SystemDetail/SystemRecommendations.js
- src/Utilities/api.js
Referred links while implementing this filter: https://github.com/RedHatInsights/edge-frontend/blob/b44aa2ca26f5a401532d8d049127c3480e8a654e/src/Routes/Devices/Devices.js
+ adding @karelhala & @terezanovotna into loop for review
Attaching screenshot for review -
@karelhala, after adding a name filter I am giving call to request recommendation list. Below GIF file is not very clear but if you see while adding/removing text from filter below there is a little shifting or fluctuation I would say while table re-rendering.
I think it should update HTML smoothly so I would like to know whether it is due to component re-rendering or something needs to fix on component side?
> RHIROS-109 - apply name filter on recommendations

- src/Components/SystemDetail/SystemRecommendations.js
- src/Components/SystemDetail/SystemRecommendations.scss
With reference to mockup page - https://marvelapp.com/prototype/9408d9j/screen/77819763
Before: Title 'Recommendations' was shown on the card
After:
+ adding @karelhala & @terezanovotna into loop for review
> fix recommendations title as per mockup

- src/Routes/RosPage/RosPage.js
This will ensure that a newer version of insights inventory table would not break columns.
cc @karelhala
> Disable default columns to keep it backwards compatible

- src/Routes/RosPage/RosPage.js
- src/store/entitiesReducer.js
With commit changes, disabling redirection links on ROS system list to avoid below scenario where two empty states are shown on system detail page, 
This is a very rare scenario when user tries to access ROS systems page when any system(s) either deleted from inventory but deletion of respective records from ROS is yet to happen OR marked as culled but a job which triggers deletion from DB not yet executed.
After disabling redirection links, systems list look like below screenshot. Added tooltip to indicate that a particular system is deleted from inventory.
+ adding @karelhala, @terezanovotna and @kuklas into loop for review
> RHIROS-222 - disable redirection links for deleted/culled systems

- src/Components/RosTable/ProgressScoreBar.js
- src/Components/RosTable/ProgressScoreBar.test.js
- src/Components/RosTable/__snapshots__/ProgressScoreBar.test.js.snap
- src/Routes/RosPage/RosPage.js
- src/store/entitiesReducer.js
With this commit, it shows "{cpu/memory/IO} score" to  "{cpu/memory/IO} utilization" and percentage(%) values instead of 1-5 score.
Screenshot for reference - 
+adding @karelhala, @terezanovotna and @kuklas into loop for review
Required backend [PR-106](https://github.com/RedHatInsights/ros-backend/pull/106) change
> RHIROS-262 - rename score(1-5) to utilization(%)

- .travis.yml
Background:
As team we discussed regarding if we want to receive the slack notifications for the travis builds of ros-frontend repository and we concluded that for now we are fine with the email notifications from the GitHub and its okay if we don't receive build notifications over the slack channel. Hence I have updated the travis.yml file to remove the step.
> updated travis.yml to remove slack notification step

- src/AppEntry.js
- src/store/index.js
Background:
We were facing 'store already initliazed' error on ROS service page while switching between ROS service and other services. This PR fixes the issue.
Jira Card: https://issues.redhat.com/browse/RHIROS-388
> RHIROS-388 - fixed store already initialized error

- src/AppEntry.js
**Background:**
There was an issue in the prod env while creating the store as due to the below condition in the init method 'false' was getting passed in the production environment hence resulting in error `middleware is not a function` while store creation.
```
init(process.env.NODE_ENV !== 'production' && logger)
``` 
**Discussion link:** https://ansible.slack.com/archives/C023VGW21NU/p1637749400317400
In this PR I have updated the code to fix the above issue.
**Steps to test:**
* update the `NODE_ENV` value between `development` and production` in the `start` script of the `package.json` file and observe the behaviour. It should work fine in both scenarios.
> fixed store creation condition causing issue in prod env

- src/Components/SystemDetail/RecommendationsTable.js
- src/Components/SystemDetail/RecommendationsTable.scss
- src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
These changes are required to test the new rules content in the UI. Test with [RHIROS-424](https://issues.redhat.com/browse/RHIROS-424) (for backend changes) and [RHIROS-404](https://issues.redhat.com/browse/RHIROS-404) (new rules content in the seed file).
> RHIROS-379 show rules content with newline and tab space

- src/Components/RosTable/SystemState.js
Updated icon color for Under pressure state as per https://issues.redhat.com/browse/RHIROS-421
Screenshot:
> RHIROS-421 updated under-pressure state icon color

- src/constants.js
This PR is needed for upgrading api routes from v0 to v1 on frontend side also. We have already fixed on the backend side [https://issues.redhat.com/browse/RHIROS-426](https://issues.redhat.com/browse/RHIROS-426)
> RHIROS-426 changed the value for ROS_API_ROOT to '/api/ros/v1'

- src/Components/ServiceNotConfigured/ServiceNotConfigured.js
- src/constants.js
Since we have documented how to enable ROS with and without Ansible, instead of showing a long page with instructions and maintaining those instructions in two places (docs and ros-frontend), let's just show link to getting started docs.
Jira:  https://issues.redhat.com/browse/RHIROS-442
Screenshot:
> [RHIROS-442] Update ROS not configured page

- src/Components/ServiceNotConfigured/ServiceNotConfigured.js
The `Getting started documentation` button has . in it, this PR fixes that.
> fixed typo for getting started button

- config/dev.webpack.config.js
- config/prod.webpack.config.js
From the version [@redhat-cloud-services/frontend-components/v/3.3.14](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components/v/3.3.14) from this PR [RedHatInsights/frontend-components/pull/1239](https://github.com/RedHatInsights/frontend-components/pull/1239) it's not required to pass custom sass prefix to apply styles from/to different application. On contrary ROS app was affecting inventory by changing the inventory table styling.
> Disable sass prefix, AsyncComponent wraps now component with correct namespace

- src/Components/SystemDetail/RecommendationsTable.js
For historical reasons (when we used to talk about "risks"), our wording when there are no suggestions is a bit convoluted. Let's simplify it.
> Simpler wording for the no suggestions case

- config/dev.webpack.config.js
- package.json
- src/Routes.js
Updated dev.webpack.config.js to use webpack proxy as [insights-proxy](https://github.com/RedHatInsights/insights-proxy) project is deprecated.
Also updated the config to run it in stage env by default and added scripts for  beta and prod environments.
Jira: https://issues.redhat.com/browse/RHIROS-229
> updated dev webpack config to use webpack proxy

- src/App.js
RBAC permissions are getting cached at the moment which means until we won't reload ROS page it will not get updated.
Jira: https://issues.redhat.com/browse/RHIROS-508
Slack thread: https://ansible.slack.com/archives/C02T90PLJ5V/p1643300401179300
Docs: https://github.com/RedHatInsights/frontend-components/blob/master/packages/docs/pages/chrome/chrome-api.md#getuserpermissions
https://drive.google.com/file/d/1cnXqI6o9HKO3XkcJlSAJkY9wnUNtox66/view?usp=sharing
> RHIROS-508 fixed RBAC permission cache issue

- src/Components/Modals/ManageColumnsModal.js
- src/constants.js
**Fixed bug:**  the os columne name in modal as raised by QE team in jira card: https://issues.redhat.com/browse/RHIROS-518
> Ref-RHIROS-518 fixed OS column name in modal

- package-lock.json
- package.json
- src/Components/Reports/Util.js
- src/Components/Reports/Util.test.js
- src/Components/Reports/UtilTestData.js
- src/Components/RosTable/RenderColumn.js
- src/constants.js
Refactored code to add `<DateFormat />` component from FEC library to be consistent with other services.
Jira: https://issues.redhat.com/browse/RHIROS-579
[Inventory Entities.js](https://github.com/RedHatInsights/insights-inventory-frontend/blob/aa81efb33c414ff6e5612befe41a028ac75948cd/src/store/entities.js#L56)
[Vulnerability report generation](https://github.com/RedHatInsights/vulnerability-ui/blob/3c42f8f392592eb3a299be5b1cbae9d7e9245798/src/Components/SmartComponents/Reports/Executive/FirstPage.js#L19)
[DateFormat Component from FEC](https://github.com/RedHatInsights/frontend-components/blob/4ccd3a53e7/packages/components/src/DateFormat/DateFormat.tsx)
[dateByStringType() from FEC library](https://github.com/RedHatInsights/frontend-components/blob/4ccd3a53e7/packages/components/src/Dat …
> Ref-RHIROS-579 code refactoring: DateFormat component from FEC

- package-lock.json
Fixes: 
- https://issues.redhat.com/browse/RHIROS-823
- https://issues.redhat.com/browse/RHIROS-822
Bugzilla link: 
- https://bugzilla.redhat.com/show_bug.cgi?id=2134876
- https://bugzilla.redhat.com/show_bug.cgi?id=2134872
More info: https://github.com/webpack/loader-utils/issues/212
Prototype pollution in JS: https://learn.snyk.io/lessons/prototype-pollution/javascript/
**V2.0.4**: https://github.com/webpack/loader-utils/commits/v2.0.4
**V1.4.2**: https://github.com/webpack/loader-utils/commits/v1.4.2
1. Run `npm audit` to check all the vulnerabilities in the project, and scroll to see loader-utils related issues and affected packages
2. Run `npm update loader-utils` to update the package to the version in which issues are fixed. And then run `npm audit` to check which vulnerabilities …
> RHIROS-823 updated loader-utils package version to fix a CVE

- src/Routes/RosPage/RosPage.js
Due to the recent changes made in the `getEntities` api method on the insight-inventory-frontend [(PR for reference](https://github.com/RedHatInsights/insights-inventory-frontend/pull/1713/files)) the host api was also using the props value `orderBy` and `orderDirection` which was passed in the config object while making `getEntities` call (Check `fetchInventoryDetails` method) and hence report_date was passed in `orderBy` value which doesn't exist on the ineventory side it was giving error during the GET hosts API request. This PR fixes the issue by passing the undefined value for both `orderBy` and `orderDirection` config options while making inventory host API request.
**Note:** the inventory side of changes are only available in the stage-beta hence this issue was only coming in the …
> RHIROS-905 fixed host API 400 error

- .travis.yml
- build_deploy.sh
- pr_check.sh
updated node version from `14` to `16` (npm v8.19.3) in travis.yml file to fix the below CVE as it was fixed in the `npm 8.4.1`
**Jira:**
https://issues.redhat.com/browse/RHIROS-526
**Bugzilla:**
https://bugzilla.redhat.com/show_bug.cgi?id=2050282
**References**
* https://docs.npmjs.com/cli/v9/commands/npm-ci
* https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_step_3_add_build_and_pr_check_scripts
**Travis Screenshot:**
> updated node version to 16 

- src/Routes/RosPage/ros-page.scss
- If we are on the first page/last page of the ROS landing page then `Go to previous page` and `Go to next page` buttons are disabled(grey) respectively. 
**First page**
**Last page**
- ROS landing page - when no systems are found
- ROS details page
> RHIROS-747 disable pagination when no systems

- src/Components/Reports/Common/ExecutiveFirstPage.js
the color codes in the breakdown of occurence section of executive report were different from the pie chart. This PR fixes the issue
Jira: https://issues.redhat.com/browse/RHIROS-909
> RHIROS-909 fixed color codes for occurance table

- src/Routes/RosPage/RosPage.js
[RHIROS-967](https://issues.redhat.com/browse/RHIROS-967) fix grammatical content for PDF option under export dropdown
Consistency to be maintained for all options present under export dropdown
> RHIROS-967 fixed grammatical content for PDF option under export

- src/Components/HistoricalDataChart/UtilTestData.js
- src/Components/Reports/UtilTestData.js
Use iso format for report_date.
> RHIROS-623 fix tests for report_date format

- .dependabot/config.yml
The dependabot creates 5 version updates pr by default this limits it to 3 and we run scans weekly on sunday so prs are ready to review on monday.
> RHIROS-369 - Run Dependabot scans on Sunday

- src/App.js
- src/Routes/RosPage/RosPage.js
- src/Routes/RosSystemDetail/RosSystemDetail.js
- src/Utilities/api.js
Jira: https://issues.redhat.com/browse/RHIF-216
insights.chrome is deprecated, we need to start using useChrome hook from platform
> RHID-216 migrate to useChrome in ROS

- src/Routes/RosPage/RosPage.js
We have to follow the uniform format for all the services. Many services have sub services and browser titles use hyphen to distinguish the main service of the page. Now to include the "Red Hat Insights" in the title, we need a better separator. It is suggested to use pipeline ' | ' as the ultimate separator in the title. 
For example. Patch has advisories, packages and systems. Each of the sub-service will have name of the main service i.e. Patch after its name in the browser title.  Example of the same: Advisories - Patch | Red Hat Insights
Suggested format : ```Sub Service - Service | Red Hat Insights```
Feel free to add any other relevant details …
> RHIROS-1051 Browser Titles Correction

- src/Routes/RosPage/RosPage.js
Show `No versions available` for OS filtering when no system.
> RHIROS-1042 add 'no versions available' in OS version filter

- src/Components/SystemDetail/RecommendationsTable.js
- src/Components/SystemDetail/RecommendationsTable.test.js
- src/Components/SystemDetail/SystemRecommendations.js
- src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
- src/Routes/RosSystemDetail/RosSystemDetail.js
- src/constants.js
To show psi-related info under ROS details page.
Parent card : [RHIROS-663](https://issues.redhat.com/browse/RHIROS-663)
> RHIROS-1064 show psi-related info under ROS details page

- src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
- src/constants.js
Ref-RHIROS-1064 updated psi enable URL
Jira: https://issues.redhat.com/browse/RHIROS-1064
> Ref-RHIROS-1064 updated psi enable URL

- src/Components/ServiceNotConfigured/ServiceNotConfigured.js
As per UX, this PR passes in an ID for tracking purposes
> Adds ID to Zero State for tracking

- src/App.js
- src/Routes.js
- src/Routes/RosPage/RosPage.js
- src/Routes/RosSuggestedInstance/RosSuggestedInstance.js
- src/Routes/RosSystemDetail/RosSystemDetail.js
- src/constants.js
[RHIROS-1171](https://issues.redhat.com/browse/RHIROS-1171)
- Add `NotAuthorized` view.
- remove [deprecated](http://front-end-docs-insights.apps.ocp4.prod.psi.redhat.com/chrome/chrome-api#identifyApp) `identifyApp`.
- set document title for suggested instance type page as `Suggested Instance Types - Resource Optimization | Red Hat Insights`
- hide global tag filter.
> RHIROS-1171 no permission view for suggested instance types page

- src/Routes/RosSystemDetail/RosSystemDetail.js
This PR will push the fix to below bug into prod-stable
RHCLOUD-26437 - Remove async lifecycle hook for ROS Details route.
(cherry picked from commit e0fc43293bf0ac05fc528f5841536cd6dd25ec65)
For ROS frontend release
> Frontend Release: cherry-pick-into-prod-stable

- src/Components/RosTable/RenderColumn.js
- src/Routes/RosPage/RosPage.js
- src/constants.js
Add group column to systems table without sorting option
https://issues.redhat.com/browse/RHIROS-1215
To adapt to inventory groups feature
> RHIROS-1215 added group column to systems table

- src/Components/RosTable/RenderColumn.js
Jira: https://issues.redhat.com/browse/ESSNTL-3723
Based on recent discussion with inventory team it was decided that we will keep group links only on the inventory side and rest of the services will remove the groups links from the column. 
Hence I created PR to address the same.
Slack conversation link: https://redhat-internal.slack.com/archives/C05KZQ2Q6FJ/p1691478044968029
> Ref-RHIROS-1215 remove link from group column

- src/Routes/RosPage/RosPage.js
Fixes https://issues.redhat.com/browse/RHINENG-2806.
This removes all occurrences of the inventory groups feature flag since the feature is considered stable.
There is no need to keep the flag to avoid extra complexity.
> chore(RHINENG-2806): Remove inventory groups feature flag

- src/Routes/RosPage/RosPage.js
- src/Utilities/api.js
- src/constants.js
**Jira:** https://issues.redhat.com/browse/RHIROS-1302
> RHIROS-1302 enable group sorting

- src/Routes/RosSystemDetail/ros-details-page.scss
The margin between the delete button and Actions dropdown is 0px because of scss file. This PR restores the proper margin.
> fix inventory header margin

- package-lock.json
- package.json
- src/Components/NoEntitiesFound/NoEntitiesFound.test.js
- src/Components/RecommendationRating/RecommendationRating.js
- src/Components/RecommendationRating/RecommendationRating.test.js
- src/Components/Reports/Common/SystemsFirstPage.test.js
- src/Components/Reports/Common/SystemsTablePage.test.js
- src/Components/Reports/Common/__snapshots__/SystemsFirstPage.test.js.snap
- src/Components/Reports/Common/__snapshots__/SystemsTablePage.test.js.snap
- src/Components/RosTable/ExpandedRow.test.js
- src/Components/RosTable/ProgressScoreBar.js
- src/Components/RosTable/ProgressScoreBar.test.js
- src/Components/RosTable/__snapshots__/ExpandedRow.test.js.snap
- src/Components/SystemDetail/RecommendationsTable.test.js
- src/Components/SystemDetail/__snapshots__/RecommendationsTable.test.js.snap
Migrated unit tests from Enzym to React Testing Library. 
> RHIENG-9113 fixed jest config and added unit tests

- package-lock.json
- package.json
Upgraded following dependencies:
- Updates **cookie from 0.6.0 to 0.7.1**
- Updates **express from 4.19.2 to 4.21.1**
- Updates **body-parser from 1.20.2 to 1.20.3**
- Updates **serve-static from 1.15.0 to 1.16.2**
- Updates **send from 0.18.0 to 0.19.0**
- Updates **path-to-regexp from 0.1.7 to 0.1.10**
- Updates **@redhat-cloud-services/frontend-components-config to 6.3.1**  which updates its dependent packages **webpack-dev-serve to 5.1.0** and updates **express to 4.19.2**
-  Bumps [postcss](https://github.com/postcss/postcss) from 8.4.39 to 8.4.47.
-  Bumps [webpack](https://github.com/webpack/webpack) from 5.93.0 to 5.95.0
-  Bumps [micromatch](https://github.com/micromatch/micromatch) from 4.0.5 to 4.0.8.
- Bumps [@babel/preset-react](https://github.com/babel/babel/tree/HEAD/package …
> RHINENG-13820 - Update package dependencies
